spring:
  batch:
    initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/demo_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver