spring:
  batch:
    initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver